# Generated by Django 2.0.6 on 2018-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogId', models.IntegerField()),
                ('blogTitle', models.CharField(max_length=300)),
                ('blogDescription', models.CharField(max_length=100000)),
                ('blogPostDateTime', models.CharField(max_length=50)),
                ('blogCoverImage', models.CharField(blank=True, max_length=1000000)),
                ('blogImage', models.CharField(blank=True, max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('phone', models.IntegerField(default=200)),
                ('whywehire_message', models.CharField(blank=True, max_length=1000)),
                ('pdf_file', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='SessionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=70)),
                ('admin_password', models.CharField(max_length=20)),
                ('login_status', models.CharField(max_length=5)),
            ],
        ),
    ]
