# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webapp', '0003_auto_20180717_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostclass',
            name='blogCoverImage',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='blogpostclass',
            name='blogImage',
            field=models.CharField(blank=True, max_length=100000000),
        ),
    ]
