# Generated by Django 2.0.6 on 2018-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50)),
                ('cEmail', models.EmailField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
