# Generated by Django 2.0.6 on 2018-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180705_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentclass',
            name='commentDate',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
